### ISSUE TITLE
pass custom metaclass to dataclass

### ISSUE THREAD

**Issue by otistamp** [biqqles/dataclassy#4]
Is there a proposed way to define a dataclass with a custom metaclass? It seems like it would have to inherit from DataClassMeta and the signature of apply_metaclass takes the metaclass as a kwarg but the dataclass decorator doesn't pass along an option to override that. Currently, this is ignored:

```python
@dataclass
class DataClass(metaclass=CustomMetaClass):
    prop: str
```

**Comment by otistamp** [comment]
My use case is for a schema wrapper around pymongo/motor which defines the collection and accessor class methods as properties. I tried using dataclasses, but because of the pitfalls it just didn't quite cut it. Currently I'm using pydantic but it is too aggressive with validation and I'd like to control when validation is run (ie only when unsafe payloads come from an http request and not when the data comes out of the db).

I'll play around with it and see what happens, thanks!

**Comment by biqqles** [comment]
As you can see this has now been implemented with a new `meta` option for `@dataclass`. Let me know if you find success "merging" the metaclasses - from experience it is often tricky but rewarding to get right!
